server:
  port: 8761 # eureka serve 端口号 默认就是8761

spring:
  application:
    name: EUREKA-SERVER # 指定服务名称 注意:服务名不能出现下划线 默认服务名不区分大小写

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka # eureka server服务注册中心的地址
    fetch-registry: false  # 关闭eureka client立即注册
    register-with-eureka: false # 让当前应用仅仅是服务注册中心,剔除client

#  server:
#    enable-self-preservation: false # 关闭自我保护
#    eviction-interval-timer-in-ms: 3000 # 超时3秒自动清除