server:
  port: 9996
spring:
  application:
    name: NACOS-CLIENT
  cloud:
    nacos:
      discovery:
        server-addr: xxx:8848
        namespace: 7032877c-e4b0-48c4-9f47-4d716ea74aa3
        group: user