server:
  port: 9940
spring:
  application:
    name: OPENFEIGN-HYSTRIX
  cloud:
    # 服务注册
    consul:
      host: localhost # consul主机地址
      port: 8500 # consul端口号
      discovery:
        service-name: ${spring.application.name} # consul客户端注册名,会替换spring.application.name
        register-health-check: true # 开启健康检查

feign:
  hystrix:
    enabled: true # 开启openfeign对hystrix支持
